vich_uploader:
    db_driver: orm

    mappings:
        aliment_images:
            uri_prefix: 'img/aliments'
            upload_destination: '%kernel.project_dir%/public/img/aliments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user_contracts:
            uri_prefix: '%app.path.user_contracts%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_contracts%'   
